#spring.application.name=csrent
#server.port=8080
#
#
#spring.datasource.url=jdbc:mysql://localhost:3306/csrent
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true



spring.application.name=csrent_bd
server.port=8080

#base de datos remota en la nube
spring.datasource.url=jdbc:postgresql://ep-sparkling-poetry-a5182kej-pooler.us-east-2.aws.neon.tech/csrent_db?user=neondb_owner&password=npg_BaRgqu3yj6KE&sslmode=require
spring.datasource.password=npg_BaRgqu3yj6KE
spring.datasource.username=neondb_owner
#spring.datasource.driver-class-name=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true